# Generated by Django 4.2.7 on 2024-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20220927_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=300, null=True)),
                ('gender_guru', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('tempat_kelahiran', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=350, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=350, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
