# Generated by Django 4.2.7 on 2024-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_guru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jabatan',
            },
        ),
    ]
