# Generated by Django 5.0.6 on 2024-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_chatid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kelas', models.CharField(max_length=200)),
                ('sekolah', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('nomer_wa', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('isi_pesan', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatid',
            options={'verbose_name_plural': 'Data Chat'},
        ),
    ]
